;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: TimerCamera.asm
;;   Version: 2.6, Updated on 2015/3/4 at 22:27:47
;;  Generated by PSoC Designer 5.4.3191
;;
;;  DESCRIPTION: Timer24 User Module software implementation file
;;
;;  NOTE: User Module APIs conform to the fastcall16 convention for marshalling
;;        arguments and observe the associated "Registers are volatile" policy.
;;        This means it is the caller's responsibility to preserve any values
;;        in the X and A registers that are still needed after the API functions
;;        returns. For Large Memory Model devices it is also the caller's 
;;        responsibility to perserve any value in the CUR_PP, IDX_PP, MVR_PP and 
;;        MVW_PP registers. Even though some of these registers may not be modified
;;        now, there is no guarantee that will remain the case in future releases.
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "TimerCamera.inc"

;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  TimerCamera_EnableInt
export _TimerCamera_EnableInt
export  TimerCamera_DisableInt
export _TimerCamera_DisableInt
export  TimerCamera_Start
export _TimerCamera_Start
export  TimerCamera_Stop
export _TimerCamera_Stop
export  TimerCamera_WritePeriod
export _TimerCamera_WritePeriod
export  TimerCamera_WriteCompareValue
export _TimerCamera_WriteCompareValue
export  TimerCamera_ReadCompareValue
export _TimerCamera_ReadCompareValue
export  TimerCamera_ReadTimer
export _TimerCamera_ReadTimer
export  TimerCamera_ReadTimerSaveCV
export _TimerCamera_ReadTimerSaveCV

; The following functions are deprecated and subject to omission in future releases
;
export  TimerCamera_ReadCounter       ; obsolete
export _TimerCamera_ReadCounter       ; obsolete
export  TimerCamera_CaptureCounter    ; obsolete
export _TimerCamera_CaptureCounter    ; obsolete


AREA spim_cam_RAM (RAM,REL)

;-----------------------------------------------
;  Constant Definitions
;-----------------------------------------------


;-----------------------------------------------
; Variable Allocation
;-----------------------------------------------


AREA UserModules (ROM, REL)

.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_EnableInt
;
;  DESCRIPTION:
;     Enables this timer's interrupt by setting the interrupt enable mask bit
;     associated with this User Module. This function has no effect until and
;     unless the global interrupts are enabled (for example by using the
;     macro M8C_EnableGInt).
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    None.                    
;  RETURNS:      Nothing.
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 TimerCamera_EnableInt:
_TimerCamera_EnableInt:
   RAM_PROLOGUE RAM_USE_CLASS_1
   TimerCamera_EnableInt_M
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_DisableInt
;
;  DESCRIPTION:
;     Disables this timer's interrupt by clearing the interrupt enable
;     mask bit associated with this User Module.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    None
;  RETURNS:      Nothing
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 TimerCamera_DisableInt:
_TimerCamera_DisableInt:
   RAM_PROLOGUE RAM_USE_CLASS_1
   TimerCamera_DisableInt_M
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_Start
;
;  DESCRIPTION:
;     Sets the start bit in the Control register of this user module.  The
;     timer will begin counting on the next input clock.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    None
;  RETURNS:      Nothing
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 TimerCamera_Start:
_TimerCamera_Start:
   RAM_PROLOGUE RAM_USE_CLASS_1
   TimerCamera_Start_M
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_Stop
;
;  DESCRIPTION:
;     Disables timer operation by clearing the start bit in the Control
;     register of the LSB block.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    None
;  RETURNS:      Nothing
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
 TimerCamera_Stop:
_TimerCamera_Stop:
   RAM_PROLOGUE RAM_USE_CLASS_1
   TimerCamera_Stop_M
   RAM_EPILOGUE RAM_USE_CLASS_1
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_WritePeriod
;
;  DESCRIPTION:
;     Write the 24-bit period value into the Period register (DR1). If the
;     Timer user module is stopped, then this value will also be latched
;     into the Count register (DR0).
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: fastcall16 DWORD dwPeriodValue (passed on stack)
;  RETURNS:   Nothing
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
_TimerCamera_WritePeriod:
   RAM_PROLOGUE RAM_USE_CLASS_2
 TimerCamera_WritePeriod:
   mov   X, SP
   mov   A, [X-5]                                ; load the period registers
   mov   reg[TimerCamera_PERIOD_MSB_REG], A
   mov   A, [X-4]
   mov   reg[TimerCamera_PERIOD_ISB_REG], A
   mov   A, [X-3]
   mov   reg[TimerCamera_PERIOD_LSB_REG], A
   RAM_EPILOGUE RAM_USE_CLASS_2
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_WriteCompareValue
;
;  DESCRIPTION:
;     Writes compare value into the Compare register (DR2).
;
;     NOTE! The Timer user module must be STOPPED in order to write the
;           Compare register. (Call TimerCamera_Stop to disable).
;-----------------------------------------------------------------------------
;
;  ARGUMENTS:    fastcall16 DWORD dwCompareValue (passed on stack)
;  RETURNS:      Nothing
;  SIDE EFFECTS: 
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;
_TimerCamera_WriteCompareValue:
   RAM_PROLOGUE RAM_USE_CLASS_2
 TimerCamera_WriteCompareValue:
   mov   X, SP
   mov   A, [X-5]                                ; load the compare registers
   mov   reg[TimerCamera_COMPARE_MSB_REG], A
   mov   A, [X-4]
   mov   reg[TimerCamera_COMPARE_ISB_REG], A
   mov   A, [X-3]
   mov   reg[TimerCamera_COMPARE_LSB_REG], A
   RAM_EPILOGUE RAM_USE_CLASS_2
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_ReadCompareValue
;
;  DESCRIPTION:
;     Reads the Compare registers.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: fastcall16 DWORD * pdwCompareValue
;             (pointer: LSB in X, MSB in A)
;  RETURNS:   Nothing (but see Side Effects).
;  SIDE EFFECTS:
;    The DWORD pointed to by X takes on the value read from DR2
;
;    The A and X registers may be modified by this or future implementations
;    of this function.  The same is true for all RAM page pointer registers in
;    the Large Memory Model.  When necessary, it is the calling function's
;    responsibility to perserve their values across calls to fastcall16 
;    functions.
;          
;    Currently only the page pointer registers listed below are modified:
;          IDX_PP
;
 TimerCamera_ReadCompareValue:
_TimerCamera_ReadCompareValue:
   RAM_PROLOGUE RAM_USE_CLASS_3
   RAM_SETPAGE_IDX A 
   mov   [X], 0
   mov   A, reg[TimerCamera_COMPARE_MSB_REG]
   mov   [X+1], A
   mov   A, reg[TimerCamera_COMPARE_ISB_REG]
   mov   [X+2], A
   mov   A, reg[TimerCamera_COMPARE_LSB_REG]
   mov   [X+3], A
   RAM_EPILOGUE RAM_USE_CLASS_3
   ret

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_ReadTimerSaveCV
;
;  DESCRIPTION:
;     Retrieves the value in the Count register (DR0), preserving the
;     value in the compare register (DR2).
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: fastcall16 DWORD * pdwCount
;             (pointer: LSB in X, MSB in A, for pass-by-reference update)
;  RETURNS:   Nothing (but see Side Effects).
;  SIDE EFFECTS:
;     1) The DWORD pointed to by X takes on the value read from DR0
;     2) May cause an interrupt, if interrupt on Compare is enabled.
;     3) If enabled, Global interrupts are momentarily disabled.
;     4) The user module is stopped momentarily while the compare value is
;        restored.  This may cause the Count register to miss one or more
;        counts depending on the input clock speed.
;  
;     5) The A and X registers may be modified by this or future implementations
;        of this function.  The same is true for all RAM page pointer registers in
;        the Large Memory Model.  When necessary, it is the calling function's
;        responsibility to perserve their values across calls to fastcall16 
;        functions.
;              
;        Currently only the page pointer registers listed below are modified: 
;             IDX_PP
;
;  THEORY of OPERATION:
;     1) Read and save the Compare register.
;     2) Read the Count register, causing its data to be latched into
;        the Compare register.
;     3) Read and save the Counter value, now in the Compare register,
;        to the buffer.
;     4) Disable global interrupts
;     5) Halt the timer
;     6) Restore the Compare register values
;     7) Start the Timer again
;     8) Restore global interrupt state
;
 TimerCamera_ReadTimerSaveCV:
_TimerCamera_ReadTimerSaveCV:
 TimerCamera_ReadCounter:                        ; this name deprecated
_TimerCamera_ReadCounter:                        ; this name deprecated

   RAM_PROLOGUE RAM_USE_CLASS_3
   RAM_SETPAGE_IDX A 
   ; save the Control register on the stack
   mov   A, reg[TimerCamera_CONTROL_LSB_REG]
   push  A

   ; save the Compare register value
   mov   A, reg[TimerCamera_COMPARE_MSB_REG]
   push  A
   mov   A, reg[TimerCamera_COMPARE_ISB_REG]
   push  A
   mov   A, reg[TimerCamera_COMPARE_LSB_REG]
   push  A

   ; Read the LSB count. This latches the Count register data into the
   ; Compare register of all bytes of chained PSoC blocks!
   ; This may cause an interrupt.
   mov   A, reg[TimerCamera_COUNTER_LSB_REG]

   ; Read the Compare register, which contains the counter value
   ; and store the return result
   mov   [X], 0
   mov   A, reg[TimerCamera_COMPARE_MSB_REG]
   mov   [X+1], A
   mov   A, reg[TimerCamera_COMPARE_ISB_REG]
   mov   [X+2], A
   mov   A, reg[TimerCamera_COMPARE_LSB_REG]
   mov   [X+3], A

   ; determine current interrupt state and save in X
   mov   A, 0
   tst   reg[CPU_F], FLAG_GLOBAL_IE
   jz    .SetupStatusFlag
   mov   A, FLAG_GLOBAL_IE
.SetupStatusFlag:
   mov   X, A

   ; disable interrupts for the time being
   M8C_DisableGInt

   ; stop the timer
   TimerCamera_Stop_M

   ; Restore the Compare register
   pop   A
   mov   reg[TimerCamera_COMPARE_LSB_REG], A
   pop   A
   mov   reg[TimerCamera_COMPARE_ISB_REG], A
   pop   A
   mov   reg[TimerCamera_COMPARE_MSB_REG], A

   ; restore start state of the timer
   pop   A
   mov   reg[TimerCamera_CONTROL_LSB_REG], A

   ; push the flag register to restore on the stack
   push  X

   RAM_EPILOGUE RAM_USE_CLASS_3
   ; Use RETI because it pops a the flag register off the stack
   ; and then returns to the caller.
   reti

.ENDSECTION


.SECTION
;-----------------------------------------------------------------------------
;  FUNCTION NAME: TimerCamera_ReadTimer
;
;  DESCRIPTION:
;     Performs a software capture of the Count register.  A synchronous
;     read of the Count register is performed.  The timer is NOT stopped.
;
;     WARNING - this will cause loss of data in the Compare register.
;-----------------------------------------------------------------------------
;
;  ARGUMENTS: fastcall16 DWORD * pdwCount
;             (pointer: LSB in X, MSB in A, for pass-by-reference update)
;  RETURNS:   Nothing (but see Side Effects).
;  SIDE EFFECTS:
;     1) The DWORD pointed to by X takes on the value read from DR2.
;     2) May cause an interrupt.
;     3) The A and X registers may be modified by this or future implementations
;        of this function.  The same is true for all RAM page pointer registers in
;        the Large Memory Model.  When necessary, it is the calling function's
;        responsibility to perserve their values across calls to fastcall16 
;        functions.
;              
;        Currently only the page pointer registers listed below are modified: 
;              IDX_PP

;
;  THEORY of OPERATION:
;     1) Read the Count register - this causes the count value to be
;        latched into the Compare registers.
;     2) Read and return the Count register values from the Compare
;        registers into the return buffer.
;
 TimerCamera_ReadTimer:
_TimerCamera_ReadTimer:
 TimerCamera_CaptureCounter:                     ; this name deprecated
_TimerCamera_CaptureCounter:                     ; this name deprecated

   RAM_PROLOGUE RAM_USE_CLASS_3
   ; Read the LSB of the Count register, DR0. This latches the count data into
   ; the Compare register of all bytes of chained PSoC blocks and may cause
   ; an interrupt.
   RAM_SETPAGE_IDX A 
   mov   A, reg[TimerCamera_COUNTER_LSB_REG]

   ; Read the Compare register, which contains the counter value
   ; and store ther return result
   mov   [X], 0
   mov   A, reg[TimerCamera_COMPARE_MSB_REG]
   mov   [X+1], A
   mov   A, reg[TimerCamera_COMPARE_ISB_REG]
   mov   [X+2], A
   mov   A, reg[TimerCamera_COMPARE_LSB_REG]
   mov   [X+3], A
   RAM_EPILOGUE RAM_USE_CLASS_3
   ret

.ENDSECTION

; End of File TimerCamera.asm
