//*****************************************************************************
//*****************************************************************************
//  FILENAME: TimerCamera.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer24 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TimerCamera_INCLUDE
#define TimerCamera_INCLUDE

#include <m8c.h>

#pragma fastcall16 TimerCamera_EnableInt
#pragma fastcall16 TimerCamera_DisableInt
#pragma fastcall16 TimerCamera_Start
#pragma fastcall16 TimerCamera_Stop
#pragma fastcall16 TimerCamera_ReadTimer                // Read  DR0
#pragma fastcall16 TimerCamera_ReadTimerSaveCV          // Read  DR0
#pragma fastcall16 TimerCamera_WritePeriod              // Write DR1
#pragma fastcall16 TimerCamera_ReadCompareValue         // Read  DR2
#pragma fastcall16 TimerCamera_WriteCompareValue        // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 TimerCamera_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 TimerCamera_CaptureCounter           // Read  DR0 "Obsolete"


//-------------------------------------------------
// Prototypes of the TimerCamera API.
//-------------------------------------------------

extern void TimerCamera_EnableInt(void);                                    // Proxy  1
extern void TimerCamera_DisableInt(void);                                   // Proxy  1
extern void TimerCamera_Start(void);                                        // Proxy  1
extern void TimerCamera_Stop(void);                                         // Proxy  1
extern void TimerCamera_ReadTimer(DWORD * pdwCount);                        // Proxy  3
extern void TimerCamera_ReadTimerSaveCV(DWORD * pdwCount);                  // Proxy  3
extern void TimerCamera_WritePeriod(DWORD dwPeriod);                        // Proxy  2
extern void TimerCamera_ReadCompareValue(DWORD * pdwCompareValue);          // Proxy  3
extern void TimerCamera_WriteCompareValue(DWORD dwCompareValue);            // Proxy  2

// The following functions are deprecated.
// They may be omitted in future releases
//
extern void TimerCamera_ReadCounter(DWORD * pdwCount);          // Obsolete
extern void TimerCamera_CaptureCounter(DWORD * pdwCount);       // Obsolete


//--------------------------------------------------
// Constants for TimerCamera API's.
//--------------------------------------------------

#define TimerCamera_CONTROL_REG_START_BIT      ( 0x01 )
#define TimerCamera_INT_REG_ADDR               ( 0x0e1 )
#define TimerCamera_INT_MASK                   ( 0x40 )


//--------------------------------------------------
// Constants for TimerCamera user defined values
//--------------------------------------------------

#define TimerCamera_PERIOD                     ( 0xc350 )
#define TimerCamera_COMPARE_VALUE              ( 0x0 )


//-------------------------------------------------
// Register Addresses for TimerCamera
//-------------------------------------------------

#pragma ioport  TimerCamera_COUNTER_LSB_REG:    0x030      //Count register LSB
BYTE            TimerCamera_COUNTER_LSB_REG;
#pragma ioport  TimerCamera_COUNTER_ISB_REG:    0x034      //Count register ISB
BYTE            TimerCamera_COUNTER_ISB_REG;
#pragma ioport  TimerCamera_COUNTER_MSB_REG:    0x038      //Count register MSB
BYTE            TimerCamera_COUNTER_MSB_REG;
#pragma ioport  TimerCamera_PERIOD_LSB_REG: 0x031          //Period register LSB
BYTE            TimerCamera_PERIOD_LSB_REG;
#pragma ioport  TimerCamera_PERIOD_ISB_REG: 0x035          //Period register ISB
BYTE            TimerCamera_PERIOD_ISB_REG;
#pragma ioport  TimerCamera_PERIOD_MSB_REG: 0x039          //Period register MSB
BYTE            TimerCamera_PERIOD_MSB_REG;
#pragma ioport  TimerCamera_COMPARE_LSB_REG:    0x032      //Compare register LSB
BYTE            TimerCamera_COMPARE_LSB_REG;
#pragma ioport  TimerCamera_COMPARE_ISB_REG:    0x036      //Compare register ISB
BYTE            TimerCamera_COMPARE_ISB_REG;
#pragma ioport  TimerCamera_COMPARE_MSB_REG:    0x03a      //Compare register MSB
BYTE            TimerCamera_COMPARE_MSB_REG;
#pragma ioport  TimerCamera_CONTROL_LSB_REG:    0x033      //Control register LSB
BYTE            TimerCamera_CONTROL_LSB_REG;
#pragma ioport  TimerCamera_CONTROL_ISB_REG:    0x037      //Control register ISB
BYTE            TimerCamera_CONTROL_ISB_REG;
#pragma ioport  TimerCamera_CONTROL_MSB_REG:    0x03b      //Control register MSB
BYTE            TimerCamera_CONTROL_MSB_REG;
#pragma ioport  TimerCamera_FUNC_LSB_REG:   0x130          //Function register LSB
BYTE            TimerCamera_FUNC_LSB_REG;
#pragma ioport  TimerCamera_FUNC_ISB_REG:   0x134          //Function register ISB
BYTE            TimerCamera_FUNC_ISB_REG;
#pragma ioport  TimerCamera_FUNC_MSB_REG:   0x138          //Function register MSB
BYTE            TimerCamera_FUNC_MSB_REG;
#pragma ioport  TimerCamera_INPUT_LSB_REG:  0x131          //Input register LSB
BYTE            TimerCamera_INPUT_LSB_REG;
#pragma ioport  TimerCamera_INPUT_ISB_REG:  0x135          //Input register ISB
BYTE            TimerCamera_INPUT_ISB_REG;
#pragma ioport  TimerCamera_INPUT_MSB_REG:  0x139          //Input register MSB
BYTE            TimerCamera_INPUT_MSB_REG;
#pragma ioport  TimerCamera_OUTPUT_LSB_REG: 0x132          //Output register LSB
BYTE            TimerCamera_OUTPUT_LSB_REG;
#pragma ioport  TimerCamera_OUTPUT_ISB_REG: 0x136          //Output register ISB
BYTE            TimerCamera_OUTPUT_ISB_REG;
#pragma ioport  TimerCamera_OUTPUT_MSB_REG: 0x13a          //Output register MSB
BYTE            TimerCamera_OUTPUT_MSB_REG;
#pragma ioport  TimerCamera_INT_REG:       0x0e1           //Interrupt Mask Register
BYTE            TimerCamera_INT_REG;


//-------------------------------------------------
// TimerCamera Macro 'Functions'
//-------------------------------------------------

#define TimerCamera_Start_M \
   ( TimerCamera_CONTROL_LSB_REG |=  TimerCamera_CONTROL_REG_START_BIT )

#define TimerCamera_Stop_M  \
   ( TimerCamera_CONTROL_LSB_REG &= ~TimerCamera_CONTROL_REG_START_BIT )

#define TimerCamera_EnableInt_M   \
   M8C_EnableIntMask(  TimerCamera_INT_REG, TimerCamera_INT_MASK )

#define TimerCamera_DisableInt_M  \
   M8C_DisableIntMask( TimerCamera_INT_REG, TimerCamera_INT_MASK )

#endif
// end of file TimerCamera.h
